apiVersion: v1
kind: ServiceAccount
metadata:
  name: iothunter-sa
  namespace: iothunter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: iothunter-role
  namespace: iothunter
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: iothunter-rb
  namespace: iothunter
subjects:
  - kind: ServiceAccount
    name: iothunter-sa
    namespace: iothunter
roleRef:
  kind: Role
  name: iothunter-role
  apiGroup: rbac.authorization.k8s.io
