---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: iothunter
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'iot-gateway'
      static_configs:
      - targets: ['iot-gateway:80']
      metrics_path: /metrics
    - job_name: 'backend-processor'
      static_configs:
      - targets: ['backend-processor:80']
      metrics_path: /metrics
    - job_name: 'device-simulator'
      static_configs:
      - targets: ['device-simulator:80']
      metrics_path: /metrics
